import { createTypes } from 'reduxsauce';

export default createTypes(`
	NUTRITIONIX_AUTOCOMPLETE
	NUTRITIONIX_NATURAL_LANGUAGE
	RECEIVE_SEARCH_INSTANT_RESULTS
	RECEIVE_FOOD_ITEM_INFO
	REMOVE_SELECTED_FOOD_ITEM
	RESET_CALORIES_GOAL
	SELECT_FOOD_ITEM
	SET_CALORIE_GOAL
	UPDATE_TODAYS_CALORIES
	`);
